### ISSUE TITLE
Can't leave

### ISSUE THREAD

**Issue by CMDR-Piboy314** [CMDR-JohnAlex/CsharpRPGChallenge#1]
Can't leave the menus when you enter them.

**Comment by CMDR-JohnAlex** [comment]
**Thank you for your Issue Report**

You can't (and not allowed to) exit the main choose menu (the one that says attack, heal or move) but if you type an incorrect command in the move menu, it will say incorrect command and bring you back to the choose menu, I can make it say exiting if you say exit and not "Error not a command". In the attack menu, there won't be an exit, but there is a run away command to run from the battle.

\- @CMDR-JohnAlex
